version: '3'
services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    restart: always
    ports:
      - "5678:5678"
    volumes:
      - /home/ubuntu/n8n:/home/node/.n8n
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=rafasouza
      - N8N_BASIC_AUTH_PASSWORD=4abaff64
      - N8N_URL=https://workflows.rafasouza.dev
      - N8N_SECURE_COOKIE=true
      - N8N_WEBHOOK_URL=https://workflows.rafasouza.dev
      - N8N_HOST=workflows.rafasouza
      - NODE_ENV=production
      - WEBHOOK_URL=https://workflows.rafasouza.dev/
      - NODE_FUNCTION_ALLOW_BUILTIN=crypto,fs
      - NODE_FUNCTION_ALLOW_EXTERNAL=moment,lodash,@google-cloud/speech
    networks:
      - n8n-network

networks:
  n8n-network:
    driver: bridge